"""Regenerate the ManagedLoginBranding block of infra/auth.yml from the files in this folder.

Edit settings.json or an .svg here, then run:  python infra/branding/render.py
(CloudFormation cannot read files itself, so the images go into the template as Base64.)
"""

import base64
import json
from pathlib import Path

HERE = Path(__file__).parent
TEMPLATE = HERE.parent / "auth.yml"
BEGIN = "  # >>> branding (generated by infra/branding/render.py — edit the files there, not here)\n"
END = "  # <<< branding\n"

# Logo images (header, form, footer) must have a width:height ratio between 1:1 and 4:1,
# so wide ornaments get transparent space above and below in their viewBox.
ASSETS = [  # (file, Cognito asset category)
    ("medallion.svg", "PAGE_HEADER_LOGO"),
    ("medallion.svg", "FAVICON_SVG"),
    ("form-ornament.svg", "FORM_LOGO"),
    ("footer-text.svg", "PAGE_FOOTER_LOGO"),
    ("page-background.svg", "PAGE_BACKGROUND"),
]


def block() -> str:
    settings = json.dumps(json.loads((HERE / "settings.json").read_text()), separators=(",", ":"))
    lines = [
        BEGIN,
        "  ManagedLoginBranding:\n",
        "    Type: AWS::Cognito::ManagedLoginBranding\n",
        "    DependsOn: UserPoolDomain # a v2 domain has no sign-in page without branding\n",
        "    Properties:\n",
        "      UserPoolId: !Ref UserPool\n",
        "      ClientId: !Ref UserPoolClient\n",
        "      UseCognitoProvidedValues: false\n",
        f"      Settings: {settings}\n",
        "      Assets:\n",
    ]
    for name, category in ASSETS:
        data = base64.b64encode((HERE / name).read_bytes()).decode()
        lines += [
            f"        - Category: {category} # {name}\n",
            "          ColorMode: LIGHT\n",  # settings.json forces light mode; DYNAMIC files are not used then

            "          Extension: SVG\n",
            f"          Bytes: {data}\n",
        ]
    lines.append(END)
    return "".join(lines)


def main() -> None:
    text = TEMPLATE.read_text()
    if BEGIN in text:
        head, rest = text.split(BEGIN, 1)
        tail = rest.split(END, 1)[1]
    else:  # first run: replace the plain resource that uses Cognito's default look
        start = text.index("  ManagedLoginBranding:\n")
        end = text.index("\nOutputs:")
        head, tail = text[:start], text[end:].lstrip("\n")
        tail = "\n" + tail
    TEMPLATE.write_text(head + block() + tail)
    print(f"updated {TEMPLATE} ({len(TEMPLATE.read_bytes())} bytes)")


if __name__ == "__main__":
    main()
